name: Build PDFs

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  release:
    types: [created]

permissions:
  contents: write  # Needed for creating releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-luatex texlive-fonts-recommended texlive-latex-recommended texlive-lang-german

    - name: Prepare fonts for build
      run: |
        bash ./scripts/fetch-fonts.sh
    
    - name: Build PDFs (DE and EN) with unified template
      run: |
        bash ./build.sh
    
    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cdpm-pdfs
        path: build/*.pdf
    
    - name: Create Release and Upload PDFs
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.pdf
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload PDFs to existing Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
