name: Build PDFs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-luatex texlive-fonts-recommended texlive-latex-recommended

    - name: Fetch exact CDPM fonts
      run: |
        bash ./scripts/fetch-fonts.sh
    
    - name: Build PDFs (DE and EN) with unified template
      run: |
        bash ./build.sh
    
    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cdpm-pdfs
        path: build/*.pdf
    
    - name: Release PDFs
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
